export const SET_IS_FIRST_LOAD = "SET_IS_FIRST_LOAD";
export const SET_VIDEOS_LIST = "SET_VIDEOS_LIST";
export const SWITCH_THEME = "SWITCH_THEME";
export const SET_SESSION = "SET_SESSION";

export const SET_SIDEBAR_OPEN = "SET_SIDEBAR_OPEN";
export const SET_AVATAR_MENU_OPEN = "SET_AVATAR_MENU_OPEN";
export const SET_LOGIN_FORM_OPEN = "SET_LOGIN_FORM_OPEN";