export const SET_CURRENT_VIDEO_PLAYBACK = "SET_CURRENT_VIDEO_PLAYBACK";
export const SET_IS_FIRST_LOAD = "SET_IS_FIRST_LOAD";
export const SET_VIDEOS_LIST = "SET_VIDEOS_LIST";
export const SWITCH_THEME = "SWITCH_THEME";