const AUTH_STORAGE_KEY = 'wa_cert_authenticated';
const API_KEY ='AIzaSyApIPj8fgPabVLVRKrzL3PlitN9CtjU8Es';

const SET_SEARCH = 'SET_SEARCH';
const SET_DARK_MODE = 'SET_DARK_MODE';
const SET_ITEMS = 'SET_ITEMS';
const SET_SELECTED_VIDEO = 'SET_SELECTED_VIDEO';
const SET_RELATED_VIDEOS = 'SET_RELATED_VIDEOS';


export { AUTH_STORAGE_KEY, API_KEY, SET_SEARCH, SET_DARK_MODE, SET_ITEMS, SET_SELECTED_VIDEO, SET_RELATED_VIDEOS };
